export { default as Logo } from "./navbarimg.png";
export { default as BgImage } from "./bg_longer.png";
export { default as HeroBg } from "./home__heroBg.jpeg";
export { default as HomeHeroBg } from "./laura-wielo-jPMKPg7qtZM-unsplash (1).jpg";
export { default as MileStone } from "./67 milestone white.png";
export { default as CulturalEvent1 } from "./cultural/event_1.png";
export { default as CulturalEvent2 } from "./cultural/event_2.png";
export { default as CulturalEvent3 } from "./cultural/event_3.png";
export { default as CulturalEvent4 } from "./cultural/event_4.png";
export { default as CulturalEvent5 } from "./cultural/event_5.png";
export { default as CulturalEvent6 } from "./cultural/event_6.png";
export { default as CulturalEvent7 } from "./cultural/event_7.png";
export { default as CulturalEvent8 } from "./cultural/event_8.png";
export { default as CulturalEvent9 } from "./cultural/event_9.png";
export { default as CulturalEvent10 } from "./cultural/event_10.png";
export { default as CulturalEvent11 } from "./cultural/event_11.png";
export { default as CulturalEvent12 } from "./cultural/event_12.png";
export { default as TechBg } from "./technical.jpeg";
export { default as MgmtBg } from "./management.png";
export { default as CulturalBg } from "./cultural.jpg";
export { default as HeroChlng } from "./heros challenge white.png";
export { default as MilestoneCardBg } from "./milestone_card_bg.png";
export { default as HerosCardBg } from "./heros_card_bg.png";
export { default as HerosChallengeBg } from "./heros_challenge_bg.png";
export { default as Poc1 } from "./poc1.png";
export { default as Poc2 } from "./poc2.png";
export { default as EducateImg } from "./edu.png";
export { default as ParllaxImg } from "./parllaxImg.png";
export { default as Social } from "./core/social.jpeg";
export { default as video } from "./bla_bg.mp4";
export { default as day1 } from "./day1.png";
export { default as day2 } from "./day2.png";
export { default as day3 } from "./day3.png";
export { default as thinktank } from "./thinktank.jpg";
export { default as talkshow } from "./talkshow.jpg";
export { default as quiz } from "./quiz.jpg";
export { default as debate } from "./debate.jpg";
export { default as storytelling } from "./storytelling.jpg";
export { default as fashion } from "./fashion.jpg";
export { default as drawing } from "./drawing.jpg";
export { default as drawing2 } from "./drawing2.jpg";
export { default as singin } from "./singin.jpg";
export { default as band } from "./band.jpg";
export { default as grpdance } from "./grpdance.jpg";
export { default as solodance } from "./solodanc.jpg";
export { default as mobdanc } from "./mobdanc.jpg";
export { default as strytl2 } from "./storytel2.jpg";
export { default as pac } from "./photographi.jpg";
export { default as pac2 } from "./pac2.jpg";
export { default as hacked } from "./hacked.jpg";
export { default as roborac } from "./roborace.png";
export { default as arldrn } from "./arealdrn.jpg";
export { default as lnfol } from "./linefolrbt.jpg";
export { default as robwar } from "./robowar.jpg";
export { default as robsoc } from "./robosoc.jpg";

export { default as Badminton } from "./Badminton.jpg";
export { default as Chess } from "./chess.jpg";
export { default as Pool } from "./Pool.jpg";
export {default as tablet} from "./tablet.jpg";
export {default as lawnt} from "./lawnt.jpg";
export {default as archery} from "./archery.jpg";
export {default as basketball} from "./basketball.jpg";
export {default as cricket} from "./cricket.jpg";
export {default as volley} from "./volley.jpg";
export {default as football} from "./football.jpg";
export {default as kabadi} from "./kabadi.jpg";