export { default as Logo } from "./navbarimg.png";
export { default as BgImage } from "./bg_longer.png";
export { default as HeroBg } from "./home__heroBg.jpeg";
export { default as HomeHeroBg } from "./laura-wielo-jPMKPg7qtZM-unsplash (1).jpg";
export { default as MileStone } from "./67 milestone white.png";
export { default as CulturalEvent1 } from "./cultural/event_1.png";
export { default as CulturalEvent2 } from "./cultural/event_2.png";
export { default as CulturalEvent3 } from "./cultural/event_3.png";
export { default as CulturalEvent4 } from "./cultural/event_4.png";
export { default as CulturalEvent5 } from "./cultural/event_5.png";
export { default as CulturalEvent6 } from "./cultural/event_6.png";
export { default as CulturalEvent7 } from "./cultural/event_7.png";
export { default as CulturalEvent8 } from "./cultural/event_8.png";
export { default as CulturalEvent9 } from "./cultural/event_9.png";
export { default as CulturalEvent10 } from "./cultural/event_10.png";
export { default as CulturalEvent11 } from "./cultural/event_11.png";
export { default as CulturalEvent12 } from "./cultural/event_12.png";
export { default as TechBg } from "./technical.jpeg";
export { default as MgmtBg } from "./management.png";
export { default as CulturalBg } from "./cultural.jpg";
export { default as HeroChlng } from "./heros challenge white.png";
export { default as MilestoneCardBg } from "./milestone_card_bg.png";
export { default as HerosCardBg } from "./heros_card_bg.png";
export { default as HerosChallengeBg } from "./heros_challenge_bg.png";
export { default as Poc1 } from "./poc1.png";
export { default as Poc2 } from "./poc2.png";
export { default as EducateImg } from "./edu.png";
export { default as ParllaxImg } from "./parllaxImg.png";
export { default as Social } from "./core/social.jpeg";
